# Generated by Django 5.2.11 on 2026-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_on_dms', models.CharField(max_length=100)),
                ('sub_category_on_dms', models.CharField(max_length=100)),
                ('small_category_on_dms', models.CharField(max_length=100)),
                ('synonyms', models.TextField(help_text='Comma-separated synonyms for matching')),
            ],
        ),
        migrations.CreateModel(
            name='DMSLocation',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('pin_code', models.CharField(db_index=True, max_length=10)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
